drop table if exists member CASCADE;

create table member
(
 id bigint generated by default as identity,
 name varchar(255),
 primary key (id)
);

insert into member(name) values('spring2');

http://localhost:8082/login.jsp?jsessionid=1632cf00cc802cdd8b01d788bf3520c0